### ISSUE TITLE
Usar "#key" em vez "#label" nas mensagens

### ISSUE THREAD

**Issue by dev-luizf** [EduardoJM/joi-translation-pt-br#22]
Talvez seja mais interessante usar "#key" em vez "#label" nas mensagens, pois caso a validação seja de um array de objetos, a mensagem vai começar com "[0]meuCampo..." em vez de "meuCampo...".

No meu contexto, utilizar key foi melhor pra legibilidade. Talvez não sirva pra todos, mas fica a ideia.

**Comment by EduardoJM** [comment]
Uma questão pertinente ao uso do `#label`, nesse ponto é lidar com as labels da biblioteca Joi. Por exemplo, seguindo a ideia do código abaixo:

```js
const Joi = require('joi');
const { messages } = require('joi-translation-pt-br');

const schema = Joi.object().keys({
    items: Joi.array().items(Joi.object().keys({
        name: Joi.string().required(),
        price: Joi.number().required(),
    }))
})

const data = {
    items: [
        {
            name: "teste",
        }
    ]
}

const result = schema.validate(data, { messages });

console.log(JSON.stringify(result.error.details, undefined, 2));
```

Eu vou obter os dados de erros da seguinte forma:

```
[
  {
    "message": "\"items[0].price\" é obrigatório",
    "path": [
      "items",
      0,
      "price"
    ],
    "type": "any.required",
    "context": {
      "label": "items[0].price",
      "key": "price"
    }
  }
]
```

Mas se ao criar um schema usando labels, passo a ter a seguinte estrutura:
```js
const schema = Joi.object().keys({
    items: Joi.array().items(Joi.object().keys({
        name: Joi.string().required().label("Nome do Item"),
        price: Joi.number().required().label("Preço do Item"),
    }))
})
```

e, a partir de então, eu passo a ter o seguinte objeto de erro:

```
[
  {
    "message": "\"Preço do Item\" é obrigatório",
    "path": [
      "items",
      0,
      "price"
    ],
    "type": "any.required",
    "context": {
      "label": "Preço do Item",
      "key": "price"
    }
  }
]
```

A mensagem passa a ter uma caracterização do campo ao invés de ficar com o `items[0].price`. Aqui, para casos de uso de formulários em que desejamos anexar os erros aos campos, os dados do `path` no retorno acima são suficientes pra isso. Os mesmos dados do `path` podem servir para reconstruir a estrutura num possível retorno de 400 Bad Request em uma API rest, seguindo a mesma estrutura do envio.
